import './createEffort.cy'
import './createEffortError.cy'
import './deleteEffort.cy'
import './goToEffortsPage.cy'
import './updateEffort.cy'
import './updateEffortError.cy'
import './checkEffortsPageContent.cy'
import './createMoreEfforts.cy'
