name: Cypress Tests
on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        services:
            mongo:
                image: mongo
                env:
                    MONGO_INITDB_ROOT_USERNAME: test
                    MONGO_INITDB_ROOT_PASSWORD: password
                options: >-
                    --health-cmd "echo 'db.runCommand("ping").ok' | mongosh --quiet"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 27017:27017
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Cypress run
              uses: cypress-io/github-action@v5
              with:
                  browser: chrome
                  start: npm start
              env:
                  DATABASE_URL: mongodb://test:password@127.0.0.1:27017
            - name: Upload screenshots
              uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-snapshots
                  path: cypress/snapshots
