name: Cypress Tests
on: [push]

jobs:
    cypress-run:
        runs-on: ubuntu-latest

        services:
            mongo:
                image: mongo

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Cypress run
              uses: cypress-io/github-action@v5
              with:
                  browser: chrome
                  start: npm start
              env:
                  DATABASE_URL: mongodb://mongo
