name: Main

on: [push]

permissions:
    checks: write
    contents: read

jobs:
    run-linter:
        name: Run linter
        runs-on: ubuntu-latest

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Set up Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install Node.js dependencies
              run: npm i

            - name: Run linters
              uses: wearerequired/lint-action@v2
              with:
                  eslint: true

    run-unit-tests:
        name: Run unit tests
        runs-on: ubuntu-latest
        needs: run-linter

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v3

            - name: Set up Node.js 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16

            - name: Install Node.js dependencies
              run: npm i

            - name: Run tests
              run: npm test

    cypress-run:
        runs-on: ubuntu-latest
        needs: [run-linter, run-unit-tests]

        services:
            mongo:
                image: mongo
                env:
                    MONGO_INITDB_ROOT_USERNAME: test
                    MONGO_INITDB_ROOT_PASSWORD: password
                options: >-
                    --health-cmd "echo 'db.runCommand("ping").ok' | mongosh --quiet"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
                ports:
                    - 27017:27017
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Cypress run
              uses: cypress-io/github-action@v5
              with:
                  browser: chrome
                  start: npm start
              env:
                  DATABASE_URL: mongodb://test:password@127.0.0.1:27017
            - name: Upload screenshots
              uses: actions/upload-artifact@v3
              if: failure()
              with:
                  name: cypress-snapshots
                  path: /home/runner/work/iet-hf-2023-service-unavailable/iet-hf-2023-service-unavailable/cypress/
